CREATE USER "WEBKJW" IDENTIFIED BY "4321"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, RESOURCE TO WEBKJW;

CREATE USER "WEBDUDGH" IDENTIFIED BY "1234"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, RESOURCE TO WEBDUDGH;

COMMIT;
 
----TABLE CREATE (STOREMENUES)
CREATE TABLE STOREMENUES(
SM_STCODE NCHAR(10),
SM_CODE NCHAR(3),
SM_SCC NCHAR(2),
SM_NAME NVARCHAR2(20),
SM_SCS NCHAR(2),
SM_COLOR NCHAR(6),
SM_SICODE NCHAR(14)
) TABLESPACE USERS;

ALTER TABLE STOREMENUES
ADD CONSTRAINT SM_STCODE_CODE_PK PRIMARY KEY (SM_STCODE,SM_CODE)
MODIFY SM_SCS DEFAULT 'S1'
MODIFY SM_COLOR DEFAULT 'FFFFFF'
MODIFY SM_SICODE DEFAULT '00000000000000';


CREATE SYNONYM SM FOR STOREMENUES;
GRANT SELECT ON SM TO WEBDUDGH;
GRANT SELECT, INSERT, UPDATE ON STOREMENUES TO WEBDUDGH;


----TABLE CREATE (COSTPRICEMGR)
CREATE TABLE COSTPRICEMGR(
CP_SMSTCODE NCHAR(10),
CP_SMCODE NCHAR(3),
CP_DATE DATE,
CP_COST NUMBER(6,0),
CP_PRICE NUMBER(6,0),
CP_DISCOUNT NCHAR(2),
CP_COMMENT NVARCHAR2(10)
)TABLESPACE USERS;

CREATE SYNONYM CP FOR COSTPRICEMGR;
GRANT SELECT ON CP TO WEBDUDGH;
GRANT SELECT,INSERT,UPDATE ON COSTPRICEMGR TO WEBDUDGH;


----TABLE CREATE (ACCESSLOG)
CREATE TABLE ACCESSLOG(
AC_SESTCODE NCHAR(10),
AC_SECODE NCHAR(3),
AC_DATE DATE,
AC_IP NVARCHAR2(15),
AC_TYPE NCHAR(1)
)TABLESPACE USERS;

CREATE SYNONYM AC FOR ACCESSLOG;
GRANT SELECT ON AC TO WEBDUDGH;
GRANT SELECT, INSERT, UPDATE ON ACCESSLOG TO WEBDUDGH;

----TABLE CREATE (STORETABLES)
CREATE TABLE STORETABLES(
TA_STCODE NCHAR(10),
TA_CODE NUMBER(3),
TA_NAME NVARCHAR2(20),
TA_SEAT NUMBER(2),
TA_GCCODE NCHAR(2),
TA_TOP NVARCHAR2(4),
TA_LEFT NVARCHAR2(4),
TA_WIDTH NVARCHAR2(4),
TA_HEIGHT NVARCHAR2(4)
)TABLESPACE USERS;

CREATE SYNONYM TA FOR STORETABLES;
GRANT SELECT ON TA TO WEBDUDGH;
GRANT SELECT, INSERT, UPDATE ON STORETABLES TO WEBDUDGH;

----TABLE CREATE (GROUPCUSTOMERS)
CREATE TABLE GROUPCUSTOMERS(
GC_SGCODE NCHAR(8),
GC_CODE NCHAR(16),
GC_ID NVARCHAR2(10),
GC_NAME NVARCHAR2(5),
GC_CHECK NCHAR(8)
)TABLESPACE USERS;

CREATE SYNONYM GC FOR GROUPCUSTOMERS;
GRANT SELECT ON GC TO WEBDUDGH;
GRANT SELECT, INSERT, UPDATE ON GROUPCUSTOMERS TO WEBDUDGH;


ALTER TABLE COSTPRICEMGR
ADD CONSTRAINT CP_SMST_SM_DATE_PK
PRIMARY KEY (CP_SMSTCODE, CP_SMCODE,CP_DATE);

ALTER TABLE COSTPRICEMGR
ADD CONSTRAINT CP_SMST_SM_FK FOREIGN KEY (CP_SMSTCODE, CP_SMCODE)
REFERENCES STOREMENUES(SM_STCODE, SM_CODE);


ALTER TABLE WEBDBA.ACCESSLOG ADD CONSTRAINT
AC_SESTCODE_SECODE_DATE_PK 
PRIMARY KEY (AC_SESTCODE,AC_SECODE,AC_DATE);

ALTER TABLE STOREMENUES
ADD CONSTRAINT SM_STCODE_CODE_PK FOREIGN KEY(SM_STCODE, SM_CODE)
REFERENCES COOKDBA.STORECATEGORIES(SC_SGCODE, SC_CODE);


ALTER TABLE STORETABLES
ADD CONSTRAINT TA_STCODE_CODE_PK PRIMARY KEY(TA_STCODE, TA_CODE);

GRANT REFERENCES ON WEBDBA.STOREMENUES TO COOKDBA;

ALTER TABLE ACCESSLOG
ADD CONSTRAINT AC_SEST_SE_FK FOREIGN KEY(AC_SESTCODE, AC_SECODE)
REFERENCES COOKDBA.STOREEMPLOYEES(SE_STCODE, SE_CODE);

COMMIT;

ALTER TABLE WEBDBA.STOREMENUES ADD CONSTRAINT
SM_STCODE_SCC_FK FOREIGN KEY (SM_STCODE,SM_SCC) 
REFERENCES COOKDBA.STORECATEGORIES(SC_SGCODE,SC_CODE);


ALTER TABLE STOREMENUES
ADD CONSTRAINT SM_STCODE_FK FOREIGN KEY(SM_STCODE)
REFERENCES COOKDBA.STORES(ST_CODE);


ALTER TABLE STORETABLES
ADD CONSTRAINT TA_STCODE_GCCODE_FK FOREIGN KEY(TA_STCODE, TA_GCCODE)
REFERENCES COOKDBA.STORECATEGORIES(SC_SGCODE, SC_CODE);



COMMIT;

